[2022-10-10T15:55:48.103+0600] {processor.py:156} INFO - Started process (PID=438) to work on /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_etl_daily_data_extractor_pass_database.py
[2022-10-10T15:55:48.104+0600] {processor.py:758} INFO - Processing file /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_etl_daily_data_extractor_pass_database.py for tasks to queue
[2022-10-10T15:55:48.105+0600] {logging_mixin.py:117} INFO - [2022-10-10T15:55:48.105+0600] {dagbag.py:525} INFO - Filling up the DagBag from /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_etl_daily_data_extractor_pass_database.py
[2022-10-10T15:55:48.124+0600] {logging_mixin.py:117} INFO - [2022-10-10T15:55:48.121+0600] {dagbag.py:330} ERROR - Failed to import: /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_etl_daily_data_extractor_pass_database.py
Traceback (most recent call last):
  File "/home/saima/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_etl_daily_data_extractor_pass_database.py", line 9, in <module>
    from airflow.operators.mysql_operator import MySqlOperator
  File "/home/saima/.local/lib/python3.10/site-packages/airflow/utils/deprecation_tools.py", line 36, in getattr_with_deprecation
    return getattr(importlib.import_module(new_module), new_class_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'airflow.providers.mysql'
[2022-10-10T15:55:48.124+0600] {processor.py:770} WARNING - No viable dags retrieved from /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_etl_daily_data_extractor_pass_database.py
[2022-10-10T15:55:48.145+0600] {processor.py:178} INFO - Processing /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_etl_daily_data_extractor_pass_database.py took 0.046 seconds
[2022-10-10T15:56:19.408+0600] {processor.py:156} INFO - Started process (PID=462) to work on /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_etl_daily_data_extractor_pass_database.py
[2022-10-10T15:56:19.409+0600] {processor.py:758} INFO - Processing file /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_etl_daily_data_extractor_pass_database.py for tasks to queue
[2022-10-10T15:56:19.409+0600] {logging_mixin.py:117} INFO - [2022-10-10T15:56:19.409+0600] {dagbag.py:525} INFO - Filling up the DagBag from /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_etl_daily_data_extractor_pass_database.py
[2022-10-10T15:56:19.427+0600] {logging_mixin.py:117} INFO - [2022-10-10T15:56:19.425+0600] {dagbag.py:330} ERROR - Failed to import: /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_etl_daily_data_extractor_pass_database.py
Traceback (most recent call last):
  File "/home/saima/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_etl_daily_data_extractor_pass_database.py", line 9, in <module>
    from airflow.operators.mysql_operator import MySqlOperator
  File "/home/saima/.local/lib/python3.10/site-packages/airflow/utils/deprecation_tools.py", line 36, in getattr_with_deprecation
    return getattr(importlib.import_module(new_module), new_class_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'airflow.providers.mysql'
[2022-10-10T15:56:19.427+0600] {processor.py:770} WARNING - No viable dags retrieved from /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_etl_daily_data_extractor_pass_database.py
[2022-10-10T15:56:19.449+0600] {processor.py:178} INFO - Processing /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_etl_daily_data_extractor_pass_database.py took 0.044 seconds
[2022-10-10T15:56:50.642+0600] {processor.py:156} INFO - Started process (PID=486) to work on /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_etl_daily_data_extractor_pass_database.py
[2022-10-10T15:56:50.643+0600] {processor.py:758} INFO - Processing file /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_etl_daily_data_extractor_pass_database.py for tasks to queue
[2022-10-10T15:56:50.643+0600] {logging_mixin.py:117} INFO - [2022-10-10T15:56:50.643+0600] {dagbag.py:525} INFO - Filling up the DagBag from /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_etl_daily_data_extractor_pass_database.py
[2022-10-10T15:56:50.657+0600] {logging_mixin.py:117} INFO - [2022-10-10T15:56:50.656+0600] {dagbag.py:330} ERROR - Failed to import: /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_etl_daily_data_extractor_pass_database.py
Traceback (most recent call last):
  File "/home/saima/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_etl_daily_data_extractor_pass_database.py", line 9, in <module>
    from airflow.operators.mysql_operator import MySqlOperator
  File "/home/saima/.local/lib/python3.10/site-packages/airflow/utils/deprecation_tools.py", line 36, in getattr_with_deprecation
    return getattr(importlib.import_module(new_module), new_class_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'airflow.providers.mysql'
[2022-10-10T15:56:50.657+0600] {processor.py:770} WARNING - No viable dags retrieved from /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_etl_daily_data_extractor_pass_database.py
[2022-10-10T15:56:50.710+0600] {processor.py:178} INFO - Processing /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_etl_daily_data_extractor_pass_database.py took 0.071 seconds
[2022-10-10T15:57:21.307+0600] {processor.py:156} INFO - Started process (PID=510) to work on /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_etl_daily_data_extractor_pass_database.py
[2022-10-10T15:57:21.308+0600] {processor.py:758} INFO - Processing file /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_etl_daily_data_extractor_pass_database.py for tasks to queue
[2022-10-10T15:57:21.309+0600] {logging_mixin.py:117} INFO - [2022-10-10T15:57:21.309+0600] {dagbag.py:525} INFO - Filling up the DagBag from /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_etl_daily_data_extractor_pass_database.py
[2022-10-10T15:57:21.327+0600] {logging_mixin.py:117} INFO - [2022-10-10T15:57:21.324+0600] {dagbag.py:330} ERROR - Failed to import: /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_etl_daily_data_extractor_pass_database.py
Traceback (most recent call last):
  File "/home/saima/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_etl_daily_data_extractor_pass_database.py", line 9, in <module>
    from airflow.operators.mysql_operator import MySqlOperator
  File "/home/saima/.local/lib/python3.10/site-packages/airflow/utils/deprecation_tools.py", line 36, in getattr_with_deprecation
    return getattr(importlib.import_module(new_module), new_class_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'airflow.providers.mysql'
[2022-10-10T15:57:21.327+0600] {processor.py:770} WARNING - No viable dags retrieved from /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_etl_daily_data_extractor_pass_database.py
[2022-10-10T15:57:21.349+0600] {processor.py:178} INFO - Processing /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_etl_daily_data_extractor_pass_database.py took 0.045 seconds
[2022-10-10T15:57:52.138+0600] {processor.py:156} INFO - Started process (PID=534) to work on /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_etl_daily_data_extractor_pass_database.py
[2022-10-10T15:57:52.139+0600] {processor.py:758} INFO - Processing file /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_etl_daily_data_extractor_pass_database.py for tasks to queue
[2022-10-10T15:57:52.140+0600] {logging_mixin.py:117} INFO - [2022-10-10T15:57:52.140+0600] {dagbag.py:525} INFO - Filling up the DagBag from /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_etl_daily_data_extractor_pass_database.py
[2022-10-10T15:57:52.159+0600] {logging_mixin.py:117} INFO - [2022-10-10T15:57:52.158+0600] {dagbag.py:330} ERROR - Failed to import: /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_etl_daily_data_extractor_pass_database.py
Traceback (most recent call last):
  File "/home/saima/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_etl_daily_data_extractor_pass_database.py", line 9, in <module>
    from airflow.operators.mysql_operator import MySqlOperator
  File "/home/saima/.local/lib/python3.10/site-packages/airflow/utils/deprecation_tools.py", line 36, in getattr_with_deprecation
    return getattr(importlib.import_module(new_module), new_class_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'airflow.providers.mysql'
[2022-10-10T15:57:52.160+0600] {processor.py:770} WARNING - No viable dags retrieved from /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_etl_daily_data_extractor_pass_database.py
[2022-10-10T15:57:52.185+0600] {processor.py:178} INFO - Processing /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_etl_daily_data_extractor_pass_database.py took 0.050 seconds
[2022-10-10T15:58:22.946+0600] {processor.py:156} INFO - Started process (PID=558) to work on /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_etl_daily_data_extractor_pass_database.py
[2022-10-10T15:58:22.947+0600] {processor.py:758} INFO - Processing file /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_etl_daily_data_extractor_pass_database.py for tasks to queue
[2022-10-10T15:58:22.948+0600] {logging_mixin.py:117} INFO - [2022-10-10T15:58:22.948+0600] {dagbag.py:525} INFO - Filling up the DagBag from /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_etl_daily_data_extractor_pass_database.py
[2022-10-10T15:58:22.966+0600] {logging_mixin.py:117} INFO - [2022-10-10T15:58:22.964+0600] {dagbag.py:330} ERROR - Failed to import: /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_etl_daily_data_extractor_pass_database.py
Traceback (most recent call last):
  File "/home/saima/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_etl_daily_data_extractor_pass_database.py", line 9, in <module>
    from airflow.operators.mysql_operator import MySqlOperator
  File "/home/saima/.local/lib/python3.10/site-packages/airflow/utils/deprecation_tools.py", line 36, in getattr_with_deprecation
    return getattr(importlib.import_module(new_module), new_class_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'airflow.providers.mysql'
[2022-10-10T15:58:22.966+0600] {processor.py:770} WARNING - No viable dags retrieved from /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_etl_daily_data_extractor_pass_database.py
[2022-10-10T15:58:22.990+0600] {processor.py:178} INFO - Processing /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_etl_daily_data_extractor_pass_database.py took 0.049 seconds
[2022-10-10T15:58:53.799+0600] {processor.py:156} INFO - Started process (PID=582) to work on /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_etl_daily_data_extractor_pass_database.py
[2022-10-10T15:58:53.800+0600] {processor.py:758} INFO - Processing file /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_etl_daily_data_extractor_pass_database.py for tasks to queue
[2022-10-10T15:58:53.800+0600] {logging_mixin.py:117} INFO - [2022-10-10T15:58:53.800+0600] {dagbag.py:525} INFO - Filling up the DagBag from /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_etl_daily_data_extractor_pass_database.py
[2022-10-10T15:58:53.819+0600] {logging_mixin.py:117} INFO - [2022-10-10T15:58:53.817+0600] {dagbag.py:330} ERROR - Failed to import: /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_etl_daily_data_extractor_pass_database.py
Traceback (most recent call last):
  File "/home/saima/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_etl_daily_data_extractor_pass_database.py", line 9, in <module>
    from airflow.operators.mysql_operator import MySqlOperator
  File "/home/saima/.local/lib/python3.10/site-packages/airflow/utils/deprecation_tools.py", line 36, in getattr_with_deprecation
    return getattr(importlib.import_module(new_module), new_class_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'airflow.providers.mysql'
[2022-10-10T15:58:53.819+0600] {processor.py:770} WARNING - No viable dags retrieved from /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_etl_daily_data_extractor_pass_database.py
[2022-10-10T15:58:53.841+0600] {processor.py:178} INFO - Processing /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_etl_daily_data_extractor_pass_database.py took 0.045 seconds
