[2022-10-10T15:55:55.254+0600] {processor.py:156} INFO - Started process (PID=445) to work on /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_etl_geo_total_data_extractor.py
[2022-10-10T15:55:55.256+0600] {processor.py:758} INFO - Processing file /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_etl_geo_total_data_extractor.py for tasks to queue
[2022-10-10T15:55:55.257+0600] {logging_mixin.py:117} INFO - [2022-10-10T15:55:55.257+0600] {dagbag.py:525} INFO - Filling up the DagBag from /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_etl_geo_total_data_extractor.py
[2022-10-10T15:55:55.289+0600] {logging_mixin.py:117} INFO - [2022-10-10T15:55:55.285+0600] {dagbag.py:330} ERROR - Failed to import: /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_etl_geo_total_data_extractor.py
Traceback (most recent call last):
  File "/home/saima/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_etl_geo_total_data_extractor.py", line 9, in <module>
    from airflow.operators.mysql_operator import MySqlOperator
  File "/home/saima/.local/lib/python3.10/site-packages/airflow/utils/deprecation_tools.py", line 36, in getattr_with_deprecation
    return getattr(importlib.import_module(new_module), new_class_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'airflow.providers.mysql'
[2022-10-10T15:55:55.290+0600] {processor.py:770} WARNING - No viable dags retrieved from /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_etl_geo_total_data_extractor.py
[2022-10-10T15:55:55.386+0600] {processor.py:178} INFO - Processing /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_etl_geo_total_data_extractor.py took 0.137 seconds
[2022-10-10T15:56:25.729+0600] {processor.py:156} INFO - Started process (PID=469) to work on /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_etl_geo_total_data_extractor.py
[2022-10-10T15:56:25.730+0600] {processor.py:758} INFO - Processing file /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_etl_geo_total_data_extractor.py for tasks to queue
[2022-10-10T15:56:25.731+0600] {logging_mixin.py:117} INFO - [2022-10-10T15:56:25.731+0600] {dagbag.py:525} INFO - Filling up the DagBag from /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_etl_geo_total_data_extractor.py
[2022-10-10T15:56:25.751+0600] {logging_mixin.py:117} INFO - [2022-10-10T15:56:25.749+0600] {dagbag.py:330} ERROR - Failed to import: /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_etl_geo_total_data_extractor.py
Traceback (most recent call last):
  File "/home/saima/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_etl_geo_total_data_extractor.py", line 9, in <module>
    from airflow.operators.mysql_operator import MySqlOperator
  File "/home/saima/.local/lib/python3.10/site-packages/airflow/utils/deprecation_tools.py", line 36, in getattr_with_deprecation
    return getattr(importlib.import_module(new_module), new_class_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'airflow.providers.mysql'
[2022-10-10T15:56:25.751+0600] {processor.py:770} WARNING - No viable dags retrieved from /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_etl_geo_total_data_extractor.py
[2022-10-10T15:56:25.775+0600] {processor.py:178} INFO - Processing /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_etl_geo_total_data_extractor.py took 0.052 seconds
[2022-10-10T15:56:58.324+0600] {processor.py:156} INFO - Started process (PID=493) to work on /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_etl_geo_total_data_extractor.py
[2022-10-10T15:56:58.324+0600] {processor.py:758} INFO - Processing file /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_etl_geo_total_data_extractor.py for tasks to queue
[2022-10-10T15:56:58.325+0600] {logging_mixin.py:117} INFO - [2022-10-10T15:56:58.325+0600] {dagbag.py:525} INFO - Filling up the DagBag from /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_etl_geo_total_data_extractor.py
[2022-10-10T15:56:58.343+0600] {logging_mixin.py:117} INFO - [2022-10-10T15:56:58.341+0600] {dagbag.py:330} ERROR - Failed to import: /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_etl_geo_total_data_extractor.py
Traceback (most recent call last):
  File "/home/saima/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_etl_geo_total_data_extractor.py", line 9, in <module>
    from airflow.operators.mysql_operator import MySqlOperator
  File "/home/saima/.local/lib/python3.10/site-packages/airflow/utils/deprecation_tools.py", line 36, in getattr_with_deprecation
    return getattr(importlib.import_module(new_module), new_class_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'airflow.providers.mysql'
[2022-10-10T15:56:58.343+0600] {processor.py:770} WARNING - No viable dags retrieved from /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_etl_geo_total_data_extractor.py
[2022-10-10T15:56:58.366+0600] {processor.py:178} INFO - Processing /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_etl_geo_total_data_extractor.py took 0.045 seconds
[2022-10-10T15:57:28.658+0600] {processor.py:156} INFO - Started process (PID=517) to work on /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_etl_geo_total_data_extractor.py
[2022-10-10T15:57:28.659+0600] {processor.py:758} INFO - Processing file /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_etl_geo_total_data_extractor.py for tasks to queue
[2022-10-10T15:57:28.660+0600] {logging_mixin.py:117} INFO - [2022-10-10T15:57:28.660+0600] {dagbag.py:525} INFO - Filling up the DagBag from /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_etl_geo_total_data_extractor.py
[2022-10-10T15:57:28.680+0600] {logging_mixin.py:117} INFO - [2022-10-10T15:57:28.679+0600] {dagbag.py:330} ERROR - Failed to import: /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_etl_geo_total_data_extractor.py
Traceback (most recent call last):
  File "/home/saima/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_etl_geo_total_data_extractor.py", line 9, in <module>
    from airflow.operators.mysql_operator import MySqlOperator
  File "/home/saima/.local/lib/python3.10/site-packages/airflow/utils/deprecation_tools.py", line 36, in getattr_with_deprecation
    return getattr(importlib.import_module(new_module), new_class_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'airflow.providers.mysql'
[2022-10-10T15:57:28.680+0600] {processor.py:770} WARNING - No viable dags retrieved from /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_etl_geo_total_data_extractor.py
[2022-10-10T15:57:28.702+0600] {processor.py:178} INFO - Processing /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_etl_geo_total_data_extractor.py took 0.049 seconds
[2022-10-10T15:57:59.099+0600] {processor.py:156} INFO - Started process (PID=541) to work on /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_etl_geo_total_data_extractor.py
[2022-10-10T15:57:59.100+0600] {processor.py:758} INFO - Processing file /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_etl_geo_total_data_extractor.py for tasks to queue
[2022-10-10T15:57:59.100+0600] {logging_mixin.py:117} INFO - [2022-10-10T15:57:59.100+0600] {dagbag.py:525} INFO - Filling up the DagBag from /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_etl_geo_total_data_extractor.py
[2022-10-10T15:57:59.119+0600] {logging_mixin.py:117} INFO - [2022-10-10T15:57:59.117+0600] {dagbag.py:330} ERROR - Failed to import: /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_etl_geo_total_data_extractor.py
Traceback (most recent call last):
  File "/home/saima/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_etl_geo_total_data_extractor.py", line 9, in <module>
    from airflow.operators.mysql_operator import MySqlOperator
  File "/home/saima/.local/lib/python3.10/site-packages/airflow/utils/deprecation_tools.py", line 36, in getattr_with_deprecation
    return getattr(importlib.import_module(new_module), new_class_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'airflow.providers.mysql'
[2022-10-10T15:57:59.119+0600] {processor.py:770} WARNING - No viable dags retrieved from /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_etl_geo_total_data_extractor.py
[2022-10-10T15:57:59.144+0600] {processor.py:178} INFO - Processing /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_etl_geo_total_data_extractor.py took 0.051 seconds
[2022-10-10T15:58:30.388+0600] {processor.py:156} INFO - Started process (PID=565) to work on /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_etl_geo_total_data_extractor.py
[2022-10-10T15:58:30.388+0600] {processor.py:758} INFO - Processing file /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_etl_geo_total_data_extractor.py for tasks to queue
[2022-10-10T15:58:30.389+0600] {logging_mixin.py:117} INFO - [2022-10-10T15:58:30.389+0600] {dagbag.py:525} INFO - Filling up the DagBag from /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_etl_geo_total_data_extractor.py
[2022-10-10T15:58:30.407+0600] {logging_mixin.py:117} INFO - [2022-10-10T15:58:30.406+0600] {dagbag.py:330} ERROR - Failed to import: /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_etl_geo_total_data_extractor.py
Traceback (most recent call last):
  File "/home/saima/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_etl_geo_total_data_extractor.py", line 9, in <module>
    from airflow.operators.mysql_operator import MySqlOperator
  File "/home/saima/.local/lib/python3.10/site-packages/airflow/utils/deprecation_tools.py", line 36, in getattr_with_deprecation
    return getattr(importlib.import_module(new_module), new_class_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'airflow.providers.mysql'
[2022-10-10T15:58:30.408+0600] {processor.py:770} WARNING - No viable dags retrieved from /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_etl_geo_total_data_extractor.py
[2022-10-10T15:58:30.429+0600] {processor.py:178} INFO - Processing /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_etl_geo_total_data_extractor.py took 0.045 seconds
[2022-10-10T15:59:00.803+0600] {processor.py:156} INFO - Started process (PID=589) to work on /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_etl_geo_total_data_extractor.py
[2022-10-10T15:59:00.804+0600] {processor.py:758} INFO - Processing file /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_etl_geo_total_data_extractor.py for tasks to queue
[2022-10-10T15:59:00.804+0600] {logging_mixin.py:117} INFO - [2022-10-10T15:59:00.804+0600] {dagbag.py:525} INFO - Filling up the DagBag from /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_etl_geo_total_data_extractor.py
[2022-10-10T15:59:00.824+0600] {logging_mixin.py:117} INFO - [2022-10-10T15:59:00.821+0600] {dagbag.py:330} ERROR - Failed to import: /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_etl_geo_total_data_extractor.py
Traceback (most recent call last):
  File "/home/saima/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_etl_geo_total_data_extractor.py", line 9, in <module>
    from airflow.operators.mysql_operator import MySqlOperator
  File "/home/saima/.local/lib/python3.10/site-packages/airflow/utils/deprecation_tools.py", line 36, in getattr_with_deprecation
    return getattr(importlib.import_module(new_module), new_class_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'airflow.providers.mysql'
[2022-10-10T15:59:00.824+0600] {processor.py:770} WARNING - No viable dags retrieved from /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_etl_geo_total_data_extractor.py
[2022-10-10T15:59:00.849+0600] {processor.py:178} INFO - Processing /d/Saima/Data-Engineering/Apache-Airflow/DAG/dags/aqm_etl_geo_total_data_extractor.py took 0.049 seconds
